- name: Web App Tasks
  block:
    - name: Docker image pulling
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_image_tag }}"
        source: pull

    - name: Docker container running
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image }}"
        state: started
        ports:
          - "{{ docker_host_port }}:{{ docker_container_port }}"

    - name: Docker container wiping
      import_tasks: tasks/0-wipe.yml
      vars:
        web_app_full_wipe: true


  tags:
    - web_app