- name: Apt update
  apt:
    update_cache: true

- name: Installation of python3 and pip3
  apt:
    name:
      - python3
      - python3-pip

- name: Installation of docker
  import_tasks: install_docker.yml
  tags: docker

- name: Installation of docker-compose
  import_tasks: install_compose.yml
  tags: docker